const countryList = [
  {value: "AL", label: "Albania"},
  {value: "AD", label: "Andorra"},
  {value: "AG", label: "Antigua and Barbuda"},
  {value: "AR", label: "Argentina"},
  {value: "AM", label: "Armenia"},
  {value: "AW", label: "Aruba"},
  {value: "AU", label: "Australia"},
  {value: "AT", label: "Austria"},
  {value: "AZ", label: "Azerbaijan"},
  {value: "BS", label: "Bahamas"},
  {value: "BH", label: "Bahrain"},
  {value: "BD", label: "Bangladesh"},
  {value: "BB", label: "Barbados"},
  {value: "BY", label: "Belarus"},
  {value: "BE", label: "Belgium"},
  {value: "BZ", label: "Belize"},
  {value: "BM", label: "Bermuda"},
  {value: "BT", label: "Bhutan"},
  {value: "BO", label: "Bolivia"},
  {value: "BA", label: "Bosnia and Herzegowina"},
  {value: "BW", label: "Botswana"},
  {value: "BR", label: "Brazil"},
  {value: "VG", label: "British Virgin Islands"},
  {value: "BG", label: "Bulgaria"},
  {value: "BF", label: "Burkina Faso"},
  {value: "KH", label: "Cambodia"},
  {value: "CA", label: "Canada"},
  {value: "KY", label: "Cayman Islands"},
  {value: "CL", label: "Chile"},
  {value: "CN", label: "China"},
  {value: "CO", label: "Colombia"},
  {value: "CR", label: "Costa Rica"},
  {value: "HR", label: "Croatia"},
  {value: "CU", label: "Cuba"},
  {value: "CW", label: "Curacao"},
  {value: "CY", label: "Cyprus"},
  {value: "CZ", label: "Czech Republic"},
  {value: "DK", label: "Denmark"},
  {value: "DM", label: "Dominica"},
  {value: "DR", label: "Dominican Republic"},
  {value: "EC", label: "Ecuador"},
  {value: "EG", label: "Egypt"},
  {value: "EE", label: "Estonia"},
  {value: "ET", label: "Ethiopia"},
  {value: "FJ", label: "Fiji"},
  {value: "FI", label: "Finland"},
  {value: "FR", label: "France"},
  {value: "PF", label: "French Polynesia"},
  {value: "GE", label: "Georgia"},
  {value: "DE", label: "Germany"},
  {value: "GH", label: "Ghana"},
  {value: "GR", label: "Greece"},
  {value: "GL", label: "Greenland"},
  {value: "GD", label: "Grenada"},
  {value: "GP", label: "Guadeloupe"},
  {value: "GT", label: "Guatemala"},
  {value: "HT", label: "Haiti"},
  {value: "HN", label: "Honduras"},
  {value: "HK", label: "Hong Kong"},
  {value: "HU", label: "Hungary"},
  {value: "IS", label: "Iceland"},
  {value: "IN", label: "India"},
  {value: "ID", label: "Indonesia"},
  {value: "IR", label: "Iran"},
  {value: "IE", label: "Ireland"},
  {value: "IL", label: "Israel"},
  {value: "IT", label: "Italy"},
  {value: "JM", label: "Jamaica"},
  {value: "JP", label: "Japan"},
  {value: "JO", label: "Jordan"},
  {value: "KZ", label: "Kazakhstan"},
  {value: "KE", label: "Kenya"},
  {value: "LA", label: "Laos"},
  {value: "LV", label: "Latvia"},
  {value: "LB", label: "Lebanon"},
  {value: "LS", label: "Lesotho"},
  {value: "LI", label: "Liechtenstein"},
  {value: "LT", label: "Lithuania"},
  {value: "LU", label: "Luxembourg"},
  {value: "MO", label: "Macao"},
  {value: "MG", label: "Madagascar"},
  {value: "MW", label: "Malawi"},
  {value: "MY", label: "Malaysia"},
  {value: "MV", label: "Maldives"},
  {value: "ML", label: "Mali"},
  {value: "MT", label: "Malta"},
  {value: "MQ", label: "Martinique"},
  {value: "MR", label: "Mauritania"},
  {value: "MX", label: "Mexico"},
  {value: "FM", label: "Micronesia"},
  {value: "MC", label: "Monaco"},
  {value: "MN", label: "Mongolia"},
  {value: "ME", label: "Montenegro"},
  {value: "MA", label: "Morocco"},
  {value: "MZ", label: "Mozambique"},
  {value: "MM", label: "Myanmar"},
  {value: "NA", label: "Namibia"},
  {value: "NP", label: "Nepal"},
  {value: "NL", label: "Netherlands"},
  {value: "NZ", label: "New Zealand"},
  {value: "NI", label: "Nicaragua"},
  {value: "NO", label: "Norway"},
  {value: "PK", label: "Pakistan"},
  {value: "PA", label: "Panama"},
  {value: "PG", label: "Papua New Guinea"},
  {value: "PY", label: "Paraguay"},
  {value: "PE", label: "Peru"},
  {value: "PH", label: "Philippines"},
  {value: "PL", label: "Poland"},
  {value: "PT", label: "Portugal"},
  {value: "PR", label: "Puerto Rico"},
  {value: "QR", label: "Qatar"},
  {value: "RO", label: "Romania"},
  {value: "RU", label: "Russia"},
  {value: "RW", label: "Rwanda"},
  {value: "BL", label: "Saint Barthelemy"},
  {value: "KN", label: "Saint Kitts and Nevis"},
  {value: "LC", label: "Saint Lucia"},
  {value: "VC", label: "Saint Vincent and the Grenadines"},
  {value: "SA", label: "Saudi Arabia"},
  {value: "SN", label: "Senegal"},
  {value: "RS", label: "Serbia"},
  {value: "SC", label: "Seychelles"},
  {value: "SG", label: "Singapore"},
  {value: "SK", label: "Slovakia"},
  {value: "SI", label: "Slovenia"},
  {value: "SB", label: "Solomon Islands"},
  {value: "ZA", label: "South Africa"},
  {value: "KR", label: "South Korea"},
  {value: "ES", label: "Spain"},
  {value: "LK", label: "Sri Lanka"},
  {value: "SZ", label: "Swaziland"},
  {value: "SE", label: "Sweden"},
  {value: "CH", label: "Switzerland"},
  // {value: "US", label: "Tahiti"},
  {value: "TW", label: "Taiwan"},
  {value: "TZ", label: "Tanzania"},
  {value: "TH", label: "Thailand"},
  {value: "TT", label: "Trinidad and Tobago"},
  {value: "TN", label: "Tunisia"},
  {value: "TR", label: "Turkey"},
  {value: "TC", label: "Turks and Caicos Islands"},
  {value: "UG", label: "Uganda"},
  {value: "UA", label: "Ukraine"},
  {value: "AE", label: "United Arab Emirates"},
  {value: "GB", label: "United Kingdom"},
  {value: "US", label: "United States of America"},
  {value: "UY", label: "Uruguay"},
  {value: "VI", label: "US Virgin Islands"},
  {value: "VU", label: "Vanautu"},
  {value: "VN", label: "Vietnam"},
  {value: "ZM", label: "Zambia"},
  {value: "ZW", label: "Zimbabwe"}
]

export default countryList