// Data derived from Euromonitor International

let topCities = [
  {
    label: "Hong Kong",
    value: "HK",
    city: "Hong Kong",
    country: "Hong Kong",
    countryCode: "HK",
    rank: 1,
    rankYear: 2018,
  },
  {
    label: "Singapore",
    value: "SG",
    city: "Singapore",
    country: "Singapore",
    countryCode: "SG",
    rank: 4,
    rankYear: 2018,
  },
  {
    label: "Bangkok",
    value: "TH",
    city: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    rank: 2,
    rankYear: 2018,
  },
  {
    label: "Krabi",
    value: "TH",
    city: "Krabi",
    country: "Thailand",
    countryCode: "TH",
    rank: 100,
    rankYear: 2018,
  },
  {
    label: "London",
    value: "UK",
    city: "London",
    country: "United Kingdom",
    countryCode: "UK",
    rank: 3,
    rankYear: 2018,
  },
  {
    label: "Macau",
    value: "MO",
    city: "Macau",
    country: "Macau",
    countryCode: "MO",
    rank: 5,
    rankYear: 2018,
  },
  {
    label: "Kuala Lumpur",
    value: "MY",
    city: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    rank: 9,
    rankYear: 2018,
  },
  {
    label: "Johor Bahru",
    value: "MY",
    city: "Johor Bahru",
    country: "Malaysia",
    countryCode: "MY",
    rank: 37,
    rankYear: 2018,
  },
  {
    label: "Penang Island",
    value: "MY",
    city: "Penang Island",
    country: "Malaysia",
    countryCode: "MY",
    rank: 66,
    rankYear: 2018,
  },
  {
    label: "Shenzhen",
    value: "CN",
    city: "Shenzhen",
    country: "China",
    countryCode: "CN",
    rank: 10,
    rankYear: 2018,
  },
  {
    label: "New York City",
    value: "US",
    city: "New York City",
    country: "USA",
    countryCode: "US",
    rank: 8,
    rankYear: 2018,
  },
  {
    label: "Antalya",
    value: "TR",
    city: "Antalya",
    country: "Turkey",
    countryCode: "TR",
    rank: 16,
    rankYear: 2018,
  },
  {
    label: "Paris",
    value: "FR",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    rank: 6,
    rankYear: 2018,
  },
  {
    label: "Istanbul",
    value: "TR",
    city: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    rank: 12,
    rankYear: 2018,
  },
  {
    label: "Rome",
    value: "IT",
    city: "Rome",
    country: "Italy",
    countryCode: "IT",
    rank: 15,
    rankYear: 2018,
  },
  {
    label: "Dubai",
    value: "AE",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    rank: 7,
    rankYear: 2018,
  },
  {
    label: "Guangzhou",
    value: "CN",
    city: "Guangzhou",
    country: "China",
    countryCode: "CN",
    rank: 18,
    rankYear: 2018,
  },
  {
    label: "Phuket",
    value: "TH",
    city: "Phuket",
    country: "Thailand",
    countryCode: "TH",
    rank: 11,
    rankYear: 2018,
  },
  {
    label: "Mecca",
    value: "SA",
    city: "Mecca",
    country: "Saudi Arabia",
    countryCode: "SA",
    rank: 21,
    rankYear: 2018,
  },
  {
    label: "Pattaya",
    value: "TH",
    city: "Pattaya",
    country: "Thailand",
    countryCode: "TH",
    rank: 25,
    rankYear: 2018,
  },
  {
    label: "Taipei City",
    value: "TW",
    city: "Taipei City",
    country: "Taiwan",
    countryCode: "TW",
    rank: 17,
    rankYear: 2018,
  },
  {
    label: "Prague",
    value: "CZ",
    city: "Prague",
    country: "Czech Republic",
    countryCode: "CZ",
    rank: 20,
    rankYear: 2018,
  },
  {
    label: "Shanghai",
    value: "CN",
    city: "Shanghai",
    country: "China",
    countryCode: "CN",
    rank: 26,
    rankYear: 2018,
  },
  {
    label: "Las Vegas",
    value: "US",
    city: "Las Vegas",
    country: "USA",
    countryCode: "US",
    rank: 28,
    rankYear: 2018,
  },
  {
    label: "Miami",
    value: "US",
    city: "Miami",
    country: "USA",
    countryCode: "US",
    rank: 22,
    rankYear: 2018,
  },
  {
    label: "Barcelona",
    value: "ES",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    rank: 31,
    rankYear: 2018,
  },
  {
    label: "Moscow",
    value: "RU",
    city: "Moscow",
    country: "Russia",
    countryCode: "RU",
    rank: 48,
    rankYear: 2018,
  },
  {
    label: "Beijing",
    value: "CN",
    city: "Beijing",
    country: "China",
    countryCode: "CN",
    rank: 54,
    rankYear: 2018,
  },
  {
    label: "Los Angeles",
    value: "US",
    city: "Los Angeles",
    country: "USA",
    countryCode: "US",
    rank: 27,
    rankYear: 2018,
  },
  {
    label: "Budapest",
    value: "HU",
    city: "Budapest",
    country: "Hungary",
    countryCode: "HU",
    rank: 57,
    rankYear: 2018,
  },
  {
    label: "Vienna",
    value: "AT",
    city: "Vienna",
    country: "Austria",
    countryCode: "AT",
    rank: 34,
    rankYear: 2018,
  },
  {
    label: "Amsterdam",
    value: "NL",
    city: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    rank: 23,
    rankYear: 2018,
  },
  {
    label: "Sofia",
    value: "BG",
    city: "Sofia",
    country: "Bulgaria",
    countryCode: "BG",
    rank: null,
    rankYear: 2015,
  },
  {
    label: "Madrid",
    value: "ES",
    city: "Madrid",
    country: "Spain",
    countryCode: "ES",
    rank: 43,
    rankYear: 2018,
  },
  {
    label: "Orlando",
    value: "US",
    city: "Orlando",
    country: "USA",
    countryCode: "US",
    rank: 44,
    rankYear: 2018,
  },
  {
    label: "Ho Chi Minh City",
    value: "VN",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    countryCode: "VN",
    rank: 39,
    rankYear: 2018,
},
  {
    label: "Lima",
    value: "PE",
    city: "Lima",
    country: "Peru",
    countryCode: "PE",
    rank: 91,
    rankYear: 2018,
  },
  {
    label: "Berlin",
    value: "DE",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    rank: 36,
    rankYear: 2018,
  },
  {
    label: "Athens",
    value: "GR",
    city: "Athens",
    country: "Greece",
    countryCode: "GR",
    rank: 49,
    rankYear: 2018,
  },
  {
    label: "Heraklion",
    value: "GR",
    city: "Heraklion",
    country: "Greece",
    countryCode: "GR",
    rank: 68,
    rankYear: 2018,
  },
  {
    label: "Rhodes",
    value: "GR",
    city: "Rhodes",
    country: "Greece",
    countryCode: "GR",
    rank: 99,
    rankYear: 2018,
  },
  {
    label: "Tokyo",
    value: "JP",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    rank: 14,
    rankYear: 2018,
  },
  {
    label: "Osaka",
    value: "JP",
    city: "Osaka",
    country: "Japan",
    countryCode: "JP",
    rank: 30,
    rankYear: 2018,
  },
  {
    label: "Kyoto",
    value: "JP",
    city: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    rank: 67,
    rankYear: 2018,
  },
  {
    label: "Chiba",
    value: "JP",
    city: "Chiba",
    country: "Japan",
    countryCode: "JP",
    rank: 90,
    rankYear: 2018,
  },
  {
    label: "Warsaw",
    value: "PL",
    city: "Warsaw",
    country: "Poland",
    countryCode: "PL",
    rank: 74,
    rankYear: 2018,
  },
  {
    label: "Krakow",
    value: "PL",
    city: "Krakow",
    country: "Poland",
    countryCode: "PL",
    rank: 75,
    rankYear: 2018,
  },
  {
    label: "Chennai",
    value: "IN",
    city: "Chennai",
    country: "India",
    countryCode: "IN",
    rank: 45,
    rankYear: 2018,
  },
  {
    label: "Cairo",
    value: "EG",
    city: "Cairo",
    country: "Egypt",
    countryCode: "EG",
    rank: 50,
    rankYear: 2018,
  },
  {
    label: "Nairobi",
    value: "KE",
    city: "Nairobi",
    country: "Kenya",
    countryCode: "KE",
    rank: null,
    rankYear: 2015,
  },
  {
    label: "Hangzhou",
    value: "CN",
    city: "Hangzhou",
    country: "China",
    countryCode: "CN",
    rank: null,
    rankYear: 2015,
  },
  {
    label: "Milan",
    value: "IT",
    city: "Milan",
    country: "Italy",
    countryCode: "IT",
    rank: 32,
    rankYear: 2018,
  },
  {
    label: "San Francisco",
    value: "US",
    city: "San Francisco",
    country: "USA",
    countryCode: "US",
    rank: 73,
    rankYear: 2018,
  },
  {
    label: "Buenos Aires",
    value: "AR",
    city: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    rank: 89,
    rankYear: 2018,
  },
  {
    label: "Venice",
    value: "IT",
    city: "Venice",
    country: "Italy",
    countryCode: "IT",
    rank: 41,
    rankYear: 2018,
  },
  {
    label: "Mexico City" ,
    value: "MX",
    city: "Mexico City" ,
    country: "Mexico",
    countryCode: "MX",
    rank: 88,
    rankYear: 2018,
  },
  {
    label: "Dublin",
    value: "IE",
    city: "Dublin",
    country: "Ireland",
    countryCode: "IE",
    rank: 46,
    rankYear: 2018,
  },
  {
    label: "Seoul",
    value: "KR",
    city: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    rank: 24,
    rankYear: 2018,
  },
  {
    label: "Jeju",
    value: "KR",
    city: "Jeju",
    country: "South Korea",
    countryCode: "KR",
    rank: 87,
    rankYear: 2018,
  },
  {
    label: "Mugla",
    value: "TR",
    city: "Mugla",
    country: "Turkey",
    countryCode: "TR",
    rank: null,
    rankYear: null,
  },
  {
    label: "Mumbai",
    value: "IN",
    city: "Mumbai",
    country: "India",
    countryCode: "IN",
    rank: 19,
    rankYear: 2018,
  },
  {
    label: "Denpasar",
    value: "ID",
    city: "Denpasar",
    country: "Indonesia",
    countryCode: "ID",
    rank: 33,
    rankYear: 2018,
  },
  {
    label: "Delhi",
    value: "IN",
    city: "Delhi",
    country: "India",
    countryCode: "IN",
    rank: 13,
    rankYear: 2018,
  },
  {
    label: "Toronto",
    value: "CA",
    city: "Toronto",
    country: "Canada",
    countryCode: "CA",
    rank: 52,
    rankYear: 2018,
  },
  {
    label: "Zhuhai",
    value: "CN",
    city: "Zhuhai",
    country: "China",
    countryCode: "CN",
    rank: 65,
    rankYear: 2018,
  },
  {
    label: "St Petersburg",
    value: "RU",
    city: "St Petersburg",
    country: "Russia",
    countryCode: "RU",
    rank: 59,
    rankYear: 2018,
  },
  {
    label: "Burgas",
    value: "BG",
    city: "Burgas",
    country: "Bulgaria",
    countryCode: "BG",
    rank: null,
    rankYear: null,
  },
  {
    label: "Sydney",
    value: "AU",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    rank: 55,
    rankYear: 2018,
  },
  {
    label: "Djerba",
    value: "TN",
    city: "Djerba",
    country: "Tunisia",
    countryCode: "TN",
    rank: null,
    rankYear: null,
  },
  {
    label: "Munich",
    value: "DE",
    city: "Munich",
    country: "Germany",
    countryCode: "DE",
    rank: 56,
    rankYear: 2018,
  },
  {
    label: "Johannesburg",
    value: "ZA",
    city: "Johannesburg",
    country: "South Africa",
    countryCode: "ZA",
    rank: 38,
    rankYear: 2018,
  },
  {
    label: "Cancun",
    value: "MX",
    city: "Cancun",
    country: "Mexico",
    countryCode: "MX",
    rank: 35,
    rankYear: 2018,
  },
  {
    label: "Edirne",
    value: "TR",
    city: "Edirne",
    country: "Turkey",
    countryCode: "TR",
    rank: null,
    rankYear: null,
  },
  {
    label: "Suzhou",
    value: "CN",
    city: "Suzhou",
    country: "China",
    countryCode: "CN",
    rank: null,
    rankYear: null,
  },
  {
    label: "Bucharest",
    value: "RO",
    city: "Bucharest",
    country: "Romania",
    countryCode: "RO",
    rank: null,
    rankYear: null,
  },
  {
    label: "Punta Cana",
    value: "DR",
    city: "Punta Cana",
    country: "Dominican Republic",
    countryCode: "DR",
    rank: 58,
    rankYear: 2018,
  },
  {
    label: "Copenhagen",
    value: "DK",
    city: "Copenhagen",
    country: "Denmark",
    countryCode: "DK",
    rank: 72,
    rankYear: 2018,
  },
  {
    label: "Agra",
    value: "IN",
    city: "Agra",
    country: "India",
    countryCode: "IN",
    rank: 29,
    rankYear: 2018,
  },
  {
    label: "Jaipur",
    value: "IN",
    city: "Jaipur",
    country: "India",
    countryCode: "IN",
    rank: 42,
    rankYear: 2018,
  },
  {
    label: "Brussels",
    value: "BE",
    city: "Brussels",
    country: "Belgium",
    countryCode: "BE",
    rank: 70,
    rankYear: 2018,
  },
  {
    label: "Nice",
    value: "FR",
    city: "Nice",
    country: "France",
    countryCode: "FR",
    rank: 92,
    rankYear: 2018,
  },
  {
    label: "Chiang Mai",
    value: "TH",
    city: "Chiang Mai",
    country: "Thailand",
    countryCode: "TH",
    rank: 64,
    rankYear: 2018,
  },
  {
    label: "Sharm el-Sheikh",
    value: "EG",
    city: "Sharm el-Sheikh",
    country: "Egypt",
    countryCode: "EG",
    rank: null,
    rankYear: null,
  },
  {
    label: "Lisbon",
    value: "PT",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    rank: 62,
    rankYear: 2018,
  },
  {
    label: "Porto",
    value: "PT",
    city: "Porto",
    country: "Portugal",
    countryCode: "PT",
    rank: 96,
    rankYear: 2018,
  },
  {
    label: "East Province",
    value: "SA",
    city: "East Province",
    country: "Saudi Arabia",
    countryCode: "SA",
    rank: null,
    rankYear: null,
  },
  {
    label: "Marrakech",
    value: "MA",
    city: "Marrakech",
    country: "Morocco",
    countryCode: "MA",
    rank: 78,
    rankYear: 2018,
  },
  {
    label: "Jakarta",
    value: "ID",
    city: "Jakarta",
    country: "Indonesia",
    countryCode: "ID",
    rank: 60,
    rankYear: 2018,
  },
  {
    label: "Batam",
    value: "ID",
    city: "Batam",
    country: "Indonesia",
    countryCode: "ID",
    rank: 97,
    rankYear: 2018,
  },
  {
    label: "Manama",
    value: "BH",
    city: "Manama",
    country: "Bahrain",
    countryCode: "BH",
    rank: null,
    rankYear: null,
  },
  {
    label: "Hanoi",
    value: "VN",
    city: "Hanoi",
    country: "Vietnam",
    countryCode: "VN",
    rank: 51,
    rankYear: 2018,
  },
  // {
  //   label: "Ha Noi",
  //   value: "VN",
  //   city: "Ha Noi",
  //   country: "Vietnam",
  //   countryCode: "VN"
  // },
  {
    label: "Ha Long",
    value: "VN",
    city: "Ha Long",
    country: "Vietname",
    countryCode: "VN",
    rank: 53,
    rankYear: 2018,
  },
  {
    label: "Honolulu",
    value: "US",
    city: "Honolulu",
    country: "USA",
    countryCode: "US",
    rank: 77,
    rankYear: 2018,
  },
  {
    label: "Manila",
    value: "PH",
    city: "Manila",
    country: "Philippines",
    countryCode: "PH",
    rank: null,
    rankYear: null,
  },
  {
    label: "Guilin",
    value: "CN",
    city: "Guilin",
    country: "China",
    countryCode: "CN",
    rank: 84,
    rankYear: 2018,
  },
  {
    label: "Auckland",
    value: "NZ",
    city: "Auckland",
    country: "New Zealand",
    countryCode: "NZ",
    rank: 79,
    rankYear: 2018,
  },
  {
    label: "Siem Reap",
    value: "KH",
    city: "Siem Reap",
    country: "Cambodia",
    countryCode: "KH",
    rank: 86,
    rankYear: 2018,
  },
  {
    label: "Phnom Penh",
    value: "KH",
    city: "Phnom Penh",
    country: "Cambodia",
    countryCode: "KH",
    rank: 69,
    rankYear: 2018,
  },
  {
    label: "Sousse",
    value: "TN",
    city: "Sousse",
    country: "Tunisia",
    countryCode: "TN",
    rank: null,
    rankYear: null,
  },
  {
    label: "Amman",
    value: "JO",
    city: "Amman",
    country: "Jordan",
    countryCode: "JO",
    rank: null,
    rankYear: null,
  },
  {
    label: "Vancouver",
    value: "CA",
    city: "Vancouver",
    country: "Canada",
    countryCode: "CA",
    rank: 71,
    rankYear: 2018,
  },
  {
    label: "Abu Dhabi",
    value: "AE",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
    countryCode: "AE",
    rank: 95,
    rankYear: 2018,
  },
  {
    label: "Kiev",
    value: "UA",
    city: "Kiev",
    country: "Ukraine",
    countryCode: "UA",
    rank: null,
    rankYear: null,
  },
  {
    label: "Lviv",
    value: "UA",
    city: "Lviv",
    country: "Ukraine",
    countryCode: "UA",
    rank: 80,
    rankYear: 2018,
  },
  {
    label: "Doha",
    value: "QR",
    city: "Doha",
    country: "Qatar",
    countryCode: "QR",
    rank: 98,
    rankYear: 2018,
  },
  {
    label: "Florence",
    value: "IT",
    city: "Florence",
    country: "Italy",
    countryCode: "IT",
    rank: 47,
    rankYear: 2018,
  },
  {
    label: "Rio de Janeiro",
    value: "BR",
    city: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    rank: 94,
    rankYear: 2018,
  },
  {
    label: "Melbourne",
    value: "AU",
    city: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    rank: 76,
    rankYear: 2018,
  },
  {
    label: "Washington",
    value: "US",
    city: "Washington",
    country: "USA",
    countryCode: "US",
    rank: null,
    rankYear: null,
  },
  {
    label: "Riyadh",
    value: "SA",
    city: "Riyadh",
    country: "Saudi Arabia",
    countryCode: "SA",
    rank: 40,
    rankYear: 2018,
  },
  {
    label: "Dammam City",
    value: "SA",
    city: "Dammam City",
    country: "Saudi Arabia",
    countryCode: "SA",
    rank: 61,
    rankYear: 2018,
  },
  {
    label: "Stockholm",
    value: "SE",
    city: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    rank: 85,
    rankYear: 2018,
  },
  {
    label: "Christchurch",
    value: "NZ",
    city: "Christchurch",
    country: "New Zealand",
    countryCode: "NZ",
    rank: null,
    rankYear: null,
  },
  {
    label: "Frankfurt",
    value: "DE",
    city: "Frankfurt",
    country: "Germany",
    countryCode: "DE",
    rank: 83,
    rankYear: 2018,
  },
  {
    label: "Baku",
    value: "AZ",
    city: "Baku",
    country: "Azerbaijan",
    countryCode: "AZ",
    rank: null,
    rankYear: null,
  },
  {
    label: "Sao Paulo",
    value: "BR",
    city: "Sao Paulo",
    country: "Brazil",
    countryCode: "BR",
    rank: null,
    rankYear: null,
  },
  {
    label: "Harare",
    value: "ZW",
    city: "Harare",
    country: "Zimbabwe",
    countryCode: "ZW",
    rank: null,
    rankYear: null,
  },
  {
    label: "Kolkatta",
    value: "IN",
    city: "Kolkata",
    country: "India",
    countryCode: "IN",
    rank: 82,
    rankYear: 2018,
  },
  {
    label: "Jerusalem",
    value: "IL",
    city: "Jerusalem",
    country: "Isreal",
    countryCode: "IL",
    rank: 63,
    rankYear: 2018,
  },
  {
    label: "Tel Aviv",
    value: "IL",
    city: "Tel Aviv",
    country: "Isreal",
    countryCode: "IL",
    rank: 81,
    rankYear: 2018,
  },
  {
    label: "Nanjing",
    value: "CN",
    city: "Nanjing",
    country: "China",
    countryCode: "CN",
    rank: null,
    rankYear: null,
  },
  {
    label: "Santiago",
    value: "CL",
    city: "Santiago",
    country: "Chile",
    countryCode: "CL",
    rank: 93,
    rankYear: 2018,
  },
]

export default topCities