let topCities = [
  {city: "Hong Kong", country: "Hong Kong", countryCode: "HK"},
  {city: "Singapore", country: "Singapore", countryCode: "SG"},
  {city: "Bangkok", country: "Thailand", countryCode: "TH"},
  {city: "London", country: "United Kingdom", countryCode: "UK"},
  {city: "Macau", country: "Macau", countryCode: "MO"},
  {city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY"},
  {city: "Shenzhen", country: "China", countryCode: "CN"},
  {city: "New York City", country: "USA", countryCode: "US"},
  {city: "Antalya", country: "Turkey", countryCode: "TR"},
  {city: "Paris", country: "France", countryCode: "FR"},
  {city: "Istanbul", country: "Turkey", countryCode: "TR"},
  {city: "Rome", country: "Italy", countryCode: "IT"},
  {city: "Dubai", country: "United Arab Emirates", countryCode: "AE"},
  {city: "Guangzhou", country: "China", countryCode: "CN"},
  {city: "Phuket", country: "Thailand", countryCode: "TH"},
  {city: "Mecca", country: "Saudi Arabia", countryCode: "SA"},
  {city: "Pattaya", country: "Thailand", countryCode: "TH"},
  {city: "Taipei City", country: "Taiwan", countryCode: "TW"},
  {city: "Prague", country: "Czech Republic", countryCode: "CZ"},
  {city: "Shanghai", country: "China", countryCode: "CN"},
  {city: "Las Vegas", country: "USA", countryCode: "US"},
  {city: "Miami", country: "USA", countryCode: "US"},
  {city: "Barcelona", country: "Spain", countryCode: "ES"},
  {city: "Moscow", country: "Russia", countryCode: "RU"},
  {city: "Beijing", country: "China", countryCode: "CN"},
  {city: "Los Angeles", country: "USA", countryCode: "US"},
  {city: "Budapest", country: "Hungary", countryCode: "HU"},
  {city: "Vienna", country: "Austria", countryCode: "AT"},
  {city: "Amsterdam", country: "Netherlands", countryCode: "NL"},
  {city: "Sofia", country: "Bulgaria", countryCode: "BG"},
  {city: "Madrid", country: "Spain", countryCode: "ES"},
  {city: "Orlando", country: "USA", countryCode: "US"},
  {city: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN"},
  {city: "Lima", country: "Peru", countryCode: "PE"},
  {city: "Berlin", country: "Germany", countryCode: "DE"},
  {city: "Tokyo", country: "Japan", countryCode: "JP"},
  {city: "Warsaw", country: "Poland", countryCode: "PL"},
  {city: "Chennai", country: "India", countryCode: "IN"},
  {city: "Cairo", country: "Egypt", countryCode: "EG"},
  {city: "Nairobi", country: "Kenya", countryCode: "KE"},
  {city: "Hangzhou", country: "China", countryCode: "CN"},
  {city: "Milan", country: "Italy", countryCode: "IT"},
  {city: "San Francisco", country: "USA", countryCode: "US"},
  {city: "Buenos Aires", country: "Argentina", countryCode: "AR"},
  {city: "Venice", country: "Italy", countryCode: "IT"},
  {city: "Mexico City", country: "Mexico", countryCode: "MX"},
  {city: "Dublin", country: "Ireland", countryCode: "IE"},
  {city: "Seoul", country: "South Korea", countryCode: "KR"},
  {city: "Mugla", country: "Turkey", countryCode: "TR"},
  {city: "Mumbai", country: "India", countryCode: "IN"},
  {city: "Denpasar", country: "Indonesia", countryCode: "ID"},
  {city: "Delhi", country: "India", countryCode: "IN"},
  {city: "Toronto", country: "Canada", countryCode: "CA"},
  {city: "Zhuhai", country: "China", countryCode: "CN"},
  {city: "St Petersburg", country: "Russia", countryCode: "RU"},
  {city: "Burgas", country: "Bulgaria", countryCode: "BG"},
  {city: "Sydney", country: "Australia", countryCode: "AU"},
  {city: "Djerba", country: "Tunisia", countryCode: "TN"},
  {city: "Munich", country: "Germany", countryCode: "DE"},
  {city: "Johannesburg", country: "South Africa", countryCode: "ZA"},
  {city: "Cancun", country: "Mexico", countryCode: "MX"},
  {city: "Edirne", country: "Turkey", countryCode: "TR"},
  {city: "Suzhou", country: "China", countryCode: "CN"},
  {city: "Bucharest", country: "Romania", countryCode: "RO"},
  {city: "Punta Cana", country: "Dominican Republic", countryCode: "DR"},
  {city: "Agra", country: "India", countryCode: "IN"},
  {city: "Jaipur", country: "India", countryCode: "IN"},
  {city: "Brussels", country: "Belgium", countryCode: "BE"},
  {city: "Nice", country: "France", countryCode: "FR"},
  {city: "Chiang Mai", country: "Thailand", countryCode: "TH"},
  {city: "Sharm el-Sheikh", country: "Egypt", countryCode: "EG"},
  {city: "Lisbon", country: "Portugal", countryCode: "PT"},
  {city: "East Province", country: "Saudi Arabia", countryCode: "SA"},
  {city: "Marrakech", country: "Morocco", countryCode: "MA"},
  {city: "Jakarta", country: "Indonesia", countryCode: "ID"},
  {city: "Manama", country: "Bahrain", countryCode: "BH"},
  {city: "Hanoi", country: "Vietnam", countryCode: "VN"},
  {city: "Honolulu", country: "USA", countryCode: "US"},
  {city: "Manila", country: "Philippines", countryCode: "PH"},
  {city: "Guilin", country: "China", countryCode: "CN"},
  {city: "Auckland", country: "New Zealand", countryCode: "NZ"},
  {city: "Siem Reap", country: "Cambodia", countryCode: "KH"},
  {city: "Sousse", country: "Tunisia", countryCode: "TN"},
  {city: "Amman", country: "Jordan", countryCode: "JO"},
  {city: "Vancouver", country: "Canada", countryCode: "CA"},
  {city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE"},
  {city: "Kiev", country: "Ukraine", countryCode: "UA"},
  {city: "Doha", country: "Qatar", countryCode: "QR"},
  {city: "Florence", country: "Italy", countryCode: "IT"},
  {city: "Rio de Janeiro", country: "Brazil", countryCode: "BR"},
  {city: "Melbourne", country: "Australia", countryCode: "AU"},
  {city: "Washington", country: "USA", countryCode: "US"},
  {city: "Riyadh", country: "Saudi Arabia", countryCode: "SA"},
  {city: "Christchurch", country: "New Zealand", countryCode: "NZ"},
  {city: "Frankfurt", country: "Germany", countryCode: "DE"},
  {city: "Baku", country: "Azerbaijan", countryCode: "AZ"},
  {city: "Sao Paulo", country: "Brazil", countryCode: "BR"},
  {city: "Harare", country: "Zimbabwe", countryCode: "ZW"},
  {city: "Kolkata", country: "India", countryCode: "IN"},
  {city: "Nanjing", country: "China", countryCode: "CN"},
]

export default topCities